
target 'FontApp' do
  pod "Artsy+OSSUIFonts", :path => "../"
end
  
target 'Tests', :exclusive => true do
  pod "Artsy+OSSUIFonts", :path => "../"

  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta'
end
